In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from scipy.stats import ttest_1samp

In [2]:
df = pd.read_csv('50_Startups.csv', delimiter=';')

In [3]:
X = df.drop(['Profit'],axis=1)

y = df['Profit']

In [15]:
df[['villes','Profit']].groupby('villes').mean('Profit')

Profit
villes                   
Lyon        118774.024375
Paris       113756.446471
Strasbourg  103905.175294

### On constate que les startups de Lyon ont en moyenne un meilleur profit.

### On encode la ville afin de pouvoir utiliser la feature selection qui sinon ne marche pas avec les chaines de caractères

In [4]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
X['villes'] = labelencoder.fit_transform(X['villes'])

### Utilisation de SelectKBest avec f_regression

In [5]:
from sklearn.feature_selection import f_regression
f_regression(X,y)

(array([849.7889044 ,   2.01495972,  60.88145448,   1.13261424]),
 array([3.50032224e-32, 1.62217395e-01, 4.38107318e-10, 2.92543007e-01]))

In [6]:
X.columns

Index(['R&D', 'Administration', 'Marketing', 'villes'], dtype='object')

### f_regression
Univariate linear regression tests returning F-statistic and p-values.

Selon ce test, on constate que Administration et villes sont des variables à faible intérêt pour notre modèle.

In [7]:
from sklearn.feature_selection import SelectKBest
selector = SelectKBest(f_regression, k=2)
selector.fit_transform(X,y)

selector.get_support()

array([ True, False,  True, False])

### effectivement, SelectKBest élimine Administration et villes